I'm getting this error on ci.hudson-labs.org. Hopefully this change quiets that down.
/home/tomcat6/.hudson/cislave/workspace/plugins_subversion/subversion/src/main/java/hudson/scm/subversion/WorkspaceUpdaterDescriptor.java:38: incompatible types; no instance(s) of type variable(s) D exist so that hudson.DescriptorExtensionList<hudson.scm.subversion.WorkspaceUpdater,D> conforms to hudson.DescriptorExtensionList<hudson.scm.subversion.WorkspaceUpdater,hudson.scm.subversion.WorkspaceUpdaterDescriptor>
found   : <D>hudson.DescriptorExtensionList<hudson.scm.subversion.WorkspaceUpdater,D>
required: hudson.DescriptorExtensionList<hudson.scm.subversion.WorkspaceUpdater,hudson.scm.subversion.WorkspaceUpdaterDescriptor>
        return Hudson.getInstance().getDescriptorList(WorkspaceUpdater.class);
                                                     ^