[HUDSON-3687] This change is binary incompatible. Specifically, plugins that implements the old signature will no longer behaves as if it doesn't override the method, hence the new setUp method will be always received by its default implementation, causing stack trace like this:
FATAL: class hudson.plugins.build_timeout.BuildTimeoutWrapper needs to implement the setUp method
java.lang.UnsupportedOperationException: class hudson.plugins.build_timeout.BuildTimeoutWrapper needs to implement the setUp method
	at hudson.tasks.BuildWrapper.setUp(BuildWrapper.java:142)
	at hudson.tasks.BuildWrapper.setUp(BuildWrapper.java:130)
	at hudson.model.Build$RunnerImpl.doRun(Build.java:107)
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:354)
	at hudson.model.Run.run(Run.java:1090)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:93)
	at hudson.model.Executor.run(Executor.java:122)