Added referral handling to fix the problem reported below: ------------------- Hello,
Sorry to bother you but I am having issues getting your Hudson AD
plug-in working. 

 

We have Hudson running on a CentOS 4.6 server, this server uses MIT KRB5
for authentication and openldap for authorization against our Active
Directory for console /ssh access. I am trying to setup the AD plug-in
so we can track who initiates build processes but am getting the below
error when I enable the plug-in.

 

an 9, 2009 4:52:13 PM hudson.security.AuthenticationProcessingFilter2
onUnsuccessfulAuthentication

INFO: Login attempt failed

org.acegisecurity.BadCredentialsException: Authentication was successful
but more than one users in the directory matches the user name:
David.Neufeld; nested exception is javax.naming.PartialResultException:
Unprocessed Continuation Reference(s); remaining name 'DC=hal,DC=local'

        at
hudson.plugins.active_directory.ActiveDirectoryUnixAuthenticationProvide
r.retrieveUser(ActiveDirectoryUnixAuthenticationProvider.java:109)

        at
org.acegisecurity.providers.dao.AbstractUserDetailsAuthenticationProvide
r.authenticate(AbstractUserDetailsAuthenticationProvider.java:119)

        at
org.acegisecurity.providers.ProviderManager.doAuthentication(ProviderMan
ager.java:195)

        at
org.acegisecurity.AbstractAuthenticationManager.authenticate(AbstractAut
henticationManager.java:45)

        at
hudson.security.AuthenticationManagerProxy.authenticate(AuthenticationMa
nagerProxy.java:27)

        at
org.acegisecurity.ui.webapp.AuthenticationProcessingFilter.attemptAuthen
tication(AuthenticationProcessingFilter.java:71)

        at
org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessin
gFilter.java:252)

        at
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.jav
a:55)

        at
org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProce
ssingFilter.java:173)

        at
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.jav
a:55)

        at
org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(H
ttpSessionContextIntegrationFilter.java:249)

        at
hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessio
nContextIntegrationFilter2.java:42)

        at
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.jav
a:55)

        at
hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:
44)

        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:85)

        at
winstone.FilterConfiguration.execute(FilterConfiguration.java:195)

        at
winstone.RequestDispatcher.doFilter(RequestDispatcher.java:368)

        at
winstone.RequestDispatcher.forward(RequestDispatcher.java:333)

        at
winstone.RequestHandlerThread.processRequest(RequestHandlerThread.java:2
44)

        at
winstone.RequestHandlerThread.run(RequestHandlerThread.java:150)

        at java.lang.Thread.run(Thread.java:619)

Caused by: javax.naming.PartialResultException: Unprocessed Continuation
Reference(s); remaining name 'DC=hal,DC=local'

        at
com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2784)

        at
com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2758)

        at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1812)

        at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1735)

        at
com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContex
t.java:368)

        at
com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompos
iteDirContext.java:338)

        at
com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompos
iteDirContext.java:321)

        at
hudson.plugins.active_directory.ActiveDirectoryUnixAuthenticationProvide
r.retrieveUser(ActiveDirectoryUnixAuthenticationProvider.java:84)

        ... 20 more

 

The server uses our AD for DNS resolution and I specified the correct
domain in the AD plug-in setup portion. Have you seen this type of
behavior before and can you offer any help?

 

Thanks in advance for your help.

 

Cheers,

David Neufeld

Sr. Systems Administrator - Technical Lead

 

tel 604.608.6026

david.neufeld@alea.ca

 

Alea Software Ltd. | Building the games people play
1401 West 8th Avenue, 4th Floor, Vancouver, BC V6H 1C9 CANADA
tel 604.685.7619 * fax 604.684.0391
www.alea.ca <http://www.alea.ca/>