Merged revisions 23640,23652,23656,23658-23659,23676,23678-23681,23683-23684,23692,23694-23695,23697,23699,23701-23702,23705-23708,23731-23732,23740,23750-23751,23757,23769,23774,23778,23786-23787,23789-23791,23795-23800,23811,23819,23822,23831-23832,23835,23840,23842-23844,23860,23864,23869,23871,23874-23875 via svnmerge from https://www.dev.java.net/svn/hudson/trunk/hudson/main
................
  r23640 | mindless | 2009-11-10 16:05:45 -0800 (Tue, 10 Nov 2009) | 2 lines
  
  [FIXED HUDSON-4588] catch NPE from TestResultAction constructor and report a nicer message
................
  r23652 | mindless | 2009-11-10 20:25:05 -0800 (Tue, 10 Nov 2009) | 3 lines
  
  add missing checkPermission(CONFIGURE) to POST data to /job/{jobname}/config.xml
  (was only checking EXTENDED_READ).  Added unit test.
................
  r23656 | kohsuke | 2009-11-11 11:20:15 -0800 (Wed, 11 Nov 2009) | 1 line
  
  Supported a relative path in the custom workspace directory, which resolves from FS root of the slave.
................
  r23658 | mindless | 2009-11-11 11:45:47 -0800 (Wed, 11 Nov 2009) | 2 lines
  
  [FIXED HUDSON-4787] use latest stapler with fix so we don't redirect to "." (stapler r1241)
................
  r23659 | mindless | 2009-11-11 12:16:27 -0800 (Wed, 11 Nov 2009) | 4 lines
  
  Fix so disabled permissions are not shown in project-specific permission matrix
  (EXTENDED_READ has been exposed there since 1.325 even w/o Extended-Read plugin
   to enable that permission)
................
  r23676 | kohsuke | 2009-11-11 16:58:24 -0800 (Wed, 11 Nov 2009) | 3 lines
  
  Initialized merge tracking via "svnmerge" with revisions "1-23674" from 
  https://www.dev.java.net/svn/hudson/branches/rc
................
  r23678 | mindless | 2009-11-11 20:24:47 -0800 (Wed, 11 Nov 2009) | 2 lines
  
  [HUDSON-4822] patch from lkishalmi to return after sending redirect in doLoginEntry
................
  r23679 | kohsuke | 2009-11-12 07:08:48 -0800 (Thu, 12 Nov 2009) | 1 line
  
  Hudson's UDP broadcast/discovery now supports IP multicast
................
  r23680 | kohsuke | 2009-11-12 07:33:18 -0800 (Thu, 12 Nov 2009) | 1 line
  
  socket to channel needs to use a Socket(Input|Output)Stream
................
  r23681 | kohsuke | 2009-11-12 07:34:27 -0800 (Thu, 12 Nov 2009) | 1 line
  
  this isn't specific to Maven anymore
................
  r23683 | mindless | 2009-11-12 10:01:01 -0800 (Thu, 12 Nov 2009) | 3 lines
  
  change system property from .neverUpdate to .never to match what UpdateCenter had,
  and is documented on wiki
................
  r23684 | jglick | 2009-11-12 11:14:37 -0800 (Thu, 12 Nov 2009) | 2 lines
  
  [FIXED HUDSON-4834] If an AccessDeniedException is thrown by ACEGI, do not print a full stack trace.
  This could be a pretty normal occurrence; user might simply need to log in and retry the request.
................
  r23692 | kohsuke | 2009-11-12 18:18:09 -0800 (Thu, 12 Nov 2009) | 17 lines
  
  Merged revisions 23689-23691 via svnmerge from 
  https://svn.dev.java.net/svn/hudson/branches/rc
  
  ........
    r23689 | kohsuke | 2009-11-12 15:35:27 -0800 (Thu, 12 Nov 2009) | 1 line
    
    improved diagnosability
  ........
    r23690 | kohsuke | 2009-11-12 18:03:42 -0800 (Thu, 12 Nov 2009) | 1 line
    
    adding a probe to diagnose a sporadic test failure
  ........
    r23691 | kohsuke | 2009-11-12 18:14:21 -0800 (Thu, 12 Nov 2009) | 1 line
    
    I think this is causing a test failure in ExtendedReadPermissionTest, as the existing alice/bob/charlie users prevent the data on the disk from loading.
  ........
................
  r23694 | kohsuke | 2009-11-12 18:23:26 -0800 (Thu, 12 Nov 2009) | 1 line
  
  javadoc should now link to hudson-ci.org
................
  r23695 | kohsuke | 2009-11-12 18:54:36 -0800 (Thu, 12 Nov 2009) | 2 lines
  
  [FIXED HUDSON-4080] Node variables not passed through to Maven jobs. In 1.335.
................
  r23697 | kohsuke | 2009-11-12 18:57:22 -0800 (Thu, 12 Nov 2009) | 9 lines
  
  Merged revisions 23696 via svnmerge from 
  https://svn.dev.java.net/svn/hudson/branches/rc
  
  ........
    r23696 | kohsuke | 2009-11-12 18:56:25 -0800 (Thu, 12 Nov 2009) | 1 line
    
    JDK 6 dependency crept in
  ........
................
  r23699 | mindless | 2009-11-12 21:47:16 -0800 (Thu, 12 Nov 2009) | 2 lines
  
  [FIXED HUDSON-4831] prevent duplicate cause entries for a build
................
  r23701 | kohsuke | 2009-11-13 06:54:13 -0800 (Fri, 13 Nov 2009) | 1 line
  
  use the same version of javadoc plugin
................
  r23702 | kohsuke | 2009-11-13 07:46:07 -0800 (Fri, 13 Nov 2009) | 1 line
  
  adding one more switch
................
  r23705 | kohsuke | 2009-11-13 10:12:58 -0800 (Fri, 13 Nov 2009) | 13 lines
  
  Merged revisions 23698-23699 via svnmerge from 
  https://svn.dev.java.net/svn/hudson/branches/rc
  
  ........
    r23698 | kohsuke | 2009-11-12 19:24:53 -0800 (Thu, 12 Nov 2009) | 1 line
    
    testing if the root cause is a test failure and it's masked by the failure in tearDown
  ........
    r23699 | mindless | 2009-11-12 21:47:16 -0800 (Thu, 12 Nov 2009) | 2 lines
    
    [FIXED HUDSON-4831] prevent duplicate cause entries for a build
  ........
................
  r23706 | kohsuke | 2009-11-13 10:21:41 -0800 (Fri, 13 Nov 2009) | 1 line
  
  made the test faster and more robustby not relying on wall clock
................
  r23707 | kohsuke | 2009-11-13 10:28:37 -0800 (Fri, 13 Nov 2009) | 1 line
  
  formatting change
................
  r23708 | kohsuke | 2009-11-13 10:40:36 -0800 (Fri, 13 Nov 2009) | 1 line
  
  handle errors, too.
................
  r23731 | mindless | 2009-11-14 14:27:31 -0800 (Sat, 14 Nov 2009) | 3 lines
  
  [HUDSON-4831] Record duplicate causes again, but now update display on the build page
  to say (# times) for duplicates instead of listing them many times.
................
  r23732 | mindless | 2009-11-14 17:17:01 -0800 (Sat, 14 Nov 2009) | 2 lines
  
  [HUDSON-4831] don't wrap "(# times)" only separate line on build page
................
  r23740 | mindless | 2009-11-15 14:44:18 -0800 (Sun, 15 Nov 2009) | 3 lines
  
  [FIXED HUDSON-3057] configure RememberMeAuthenticationProvider with PAMSecurityRealm,
  so "remember me" feature works.
................
  r23750 | mindless | 2009-11-15 21:21:31 -0800 (Sun, 15 Nov 2009) | 2 lines
  
  [HUDSON-4066] Add version# is slave.jar and report this in log when a node is launched.
................
  r23751 | kohsuke | 2009-11-15 22:09:25 -0800 (Sun, 15 Nov 2009) | 14 lines
  
  Merged revisions 23731-23732 via svnmerge from 
  https://svn.dev.java.net/svn/hudson/branches/rc
  
  ........
    r23731 | mindless | 2009-11-14 14:27:31 -0800 (Sat, 14 Nov 2009) | 3 lines
    
    [HUDSON-4831] Record duplicate causes again, but now update display on the build page
    to say (# times) for duplicates instead of listing them many times.
  ........
    r23732 | mindless | 2009-11-14 17:17:01 -0800 (Sat, 14 Nov 2009) | 2 lines
    
    [HUDSON-4831] don't wrap "(# times)" only separate line on build page
  ........
................
  r23757 | mindless | 2009-11-16 10:41:05 -0800 (Mon, 16 Nov 2009) | 2 lines
  
  [FIXED HUDSON-2360] Space in axis value for matrix project was lost on reconfiguration
................
  r23769 | kohsuke | 2009-11-16 16:26:04 -0800 (Mon, 16 Nov 2009) | 13 lines
  
  Merged revisions 23766,23768 via svnmerge from 
  https://svn.dev.java.net/svn/hudson/branches/rc
  
  ........
    r23766 | kohsuke | 2009-11-16 16:23:05 -0800 (Mon, 16 Nov 2009) | 1 line
    
    [maven-release-plugin] prepare release hudson-1_334
  ........
    r23768 | kohsuke | 2009-11-16 16:23:19 -0800 (Mon, 16 Nov 2009) | 1 line
    
    [maven-release-plugin] prepare for next development iteration
  ........
................
  r23774 | kohsuke | 2009-11-16 17:06:01 -0800 (Mon, 16 Nov 2009) | 9 lines
  
  Merged revisions 23772 via svnmerge from 
  https://svn.dev.java.net/svn/hudson/branches/rc
  
  ........
    r23772 | kohsuke | 2009-11-16 17:02:11 -0800 (Mon, 16 Nov 2009) | 1 line
    
    updated changelog as a part of the release
  ........
................
  r23778 | sogabe | 2009-11-17 07:07:26 -0800 (Tue, 17 Nov 2009) | 2 lines
  
  fixed that core version in coreWarning is null. it should use requiredCore, not coreVersion.
................
  r23786 | kohsuke | 2009-11-17 12:09:40 -0800 (Tue, 17 Nov 2009) | 1 line
  
  preparing a workspace for OpenSUSE RPMs
................
  r23787 | kohsuke | 2009-11-17 13:13:38 -0800 (Tue, 17 Nov 2009) | 1 line
  
  resurrected the original scripts from http://linux01.gwdg.de/~pbleser/files/rpm/hudson/
................
  r23789 | kohsuke | 2009-11-17 13:29:51 -0800 (Tue, 17 Nov 2009) | 1 line
  
  this file is needed
................
  r23790 | kohsuke | 2009-11-17 13:39:01 -0800 (Tue, 17 Nov 2009) | 1 line
  
  reverting everything except init file to the RedHat version, since something around the fillup tool isn't working
................
  r23791 | kohsuke | 2009-11-17 13:49:28 -0800 (Tue, 17 Nov 2009) | 1 line
  
  integrated OpenSUSE RPM build to the release
................
  r23795 | kohsuke | 2009-11-17 13:59:42 -0800 (Tue, 17 Nov 2009) | 1 line
  
  typo
................
  r23796 | kohsuke | 2009-11-17 14:05:36 -0800 (Tue, 17 Nov 2009) | 1 line
  
  updated the instruction
................
  r23797 | kohsuke | 2009-11-17 14:09:02 -0800 (Tue, 17 Nov 2009) | 1 line
  
  forgot to update
................
  r23798 | kohsuke | 2009-11-17 14:25:33 -0800 (Tue, 17 Nov 2009) | 1 line
  
  sign the repo, in the OpenSUSE style
................
  r23799 | kohsuke | 2009-11-17 14:29:45 -0800 (Tue, 17 Nov 2009) | 1 line
  
  signature and key in the repodata directory does the magic, so this file is not needed
................
  r23800 | kohsuke | 2009-11-17 15:57:50 -0800 (Tue, 17 Nov 2009) | 1 line
  
  depend on Sun JRE. I could have just used 'java' as the dependency, but zypper seems to prefer OpenJDK if I do that, and I feel more comfortable with Sun JDK
................
  r23811 | mindless | 2009-11-17 22:37:09 -0800 (Tue, 17 Nov 2009) | 4 lines
  
  [FIXED HUDSON-4878] r22948 introduced a little bug in that a label with no nodes
  generates an exception when trying to get the cause of blockage (calls next() on
  empty iterator)
................
  r23819 | mindless | 2009-11-18 09:47:02 -0800 (Wed, 18 Nov 2009) | 2 lines
  
  [FIXED HUDSON-4877] Fixed handling of non-ASCII characters in external job submission
................
  r23822 | mindless | 2009-11-18 11:31:52 -0800 (Wed, 18 Nov 2009) | 3 lines
  
  [FIXED HUDSON-4890] reconnect callback to show "Done" when update is done, and
  add counter so if there are multiple update sites it shows Done when all are done.
................
  r23831 | kohsuke | 2009-11-18 15:22:00 -0800 (Wed, 18 Nov 2009) | 1 line
  
  reverting a typo introduced in r23543
................
  r23832 | mindless | 2009-11-18 15:38:20 -0800 (Wed, 18 Nov 2009) | 2 lines
  
  [FIXED HUDSON-4894] update DRIVE_PATTERN so a path like C:\ is recognized as absolute
................
  r23835 | kohsuke | 2009-11-18 17:15:19 -0800 (Wed, 18 Nov 2009) | 1 line
  
  integrated the latest htmlunit to fix a possible ConcurrentModificationException
................
  r23840 | kohsuke | 2009-11-18 17:17:09 -0800 (Wed, 18 Nov 2009) | 3 lines
  
  Initialized merge tracking via "svnmerge" with revisions "1-23838" from 
  https://www.dev.java.net/svn/hudson/branches/rc
................
  r23842 | kohsuke | 2009-11-18 17:55:02 -0800 (Wed, 18 Nov 2009) | 6 lines
  
  Adds parameters in /etc/default/hudson and /etc/init.d/hudson to set the
  max files opened limit.
  In ubuntu, the pam config for the su command does not have pam_limits.so
  enabled by default.
  I think a sane default for hudson would be to not rely in the
  distribution or the admin of the OS to manage those settings.
................
  r23843 | kohsuke | 2009-11-18 18:31:14 -0800 (Wed, 18 Nov 2009) | 35 lines
  
  Activating this by default. Exceprt from the IRC chat:
  
  (05:30:38 PM) feniix: hello kohsuke
  (05:30:43 PM) kohsuke: hi
  (05:31:23 PM) feniix: Just sent you a pull request of this commit http://github.com/feniix/hudson/commit/d13c08ea8f5a3fa730ba174305e6429b74853927
  (05:31:25 PM) feniix: :)
  (05:32:02 PM) feniix: its a workaround for the setup of the limits.conf on ubuntu and most likely debian too.
  (05:33:00 PM) kohsuke: should it be enabled by default, then?
  (05:33:18 PM) kohsuke: or maybe I should ask you why this is an issue
  (05:34:23 PM) kohsuke: Oh, maybe I misunderstand the issue
  (05:34:34 PM) kohsuke: it's to enforce ulimit?
  (05:34:48 PM) kohsuke: presumably the root has infinite ulimit and sudo don't add this?
  (05:37:18 PM) feniix: to be able to increase the max files open limits
  (05:37:30 PM) feniix: on debian, the pam config for su
  (05:37:43 PM) feniix: does not run the rules pam_limits.so
  (05:37:54 PM) feniix: so it applies the default that is 1024
  (05:38:09 PM) feniix: we have a project that has more than 3000 java files
  (05:39:02 PM) feniix: also, if the shell of a user is /bin/false being a nologin shell, does not use pam_limits.so either.
  (05:39:16 PM) feniix: even if you add:
  (05:39:47 PM) feniix: *      soft   nfiles XXXX
  (05:39:50 PM) feniix: and
  (05:40:03 PM) feniix: *     hard    nfiles XXXX in your limits.conf
  (05:40:11 PM) feniix: is not applied to the hudson user
  (05:40:27 PM) kohsuke: I see.
  (05:40:34 PM) kohsuke: So shall we enable this by default?
  (05:40:43 PM) kohsuke: I bet most Hudson users aren't aware of anything like those
  (05:40:44 PM) kohsuke: I wasn't
  (05:41:27 PM) feniix: I don't think would have to much of a negative impact to have that enabled by default
  (05:41:38 PM) feniix: could be setup to something not too big like 4096
  (05:42:02 PM) feniix: the max limit is 65535 (on 32bit at least)
  (05:42:18 PM) kohsuke: ok
  (05:44:27 PM) feniix: cool
  (05:44:36 PM) feniix: see ya
................
  r23844 | kohsuke | 2009-11-18 18:44:20 -0800 (Wed, 18 Nov 2009) | 1 line
  
  automating a remote build via Hudson
................
  r23860 | mindless | 2009-11-19 12:10:46 -0800 (Thu, 19 Nov 2009) | 2 lines
  
  Add same blurb for offlineMessage textbox in /disconnect as was added in /markOffline
................
  r23864 | kohsuke | 2009-11-19 14:24:43 -0800 (Thu, 19 Nov 2009) | 1 line
  
  Gracefully detect the double loading of JNA instead of failing later with NoClassDefFoundError.
................
  r23869 | kohsuke | 2009-11-19 14:31:07 -0800 (Thu, 19 Nov 2009) | 9 lines
  
  Merged revisions 23868 via svnmerge from 
  https://svn.dev.java.net/svn/hudson/branches/rc
  
  ........
    r23868 | kohsuke | 2009-11-19 14:30:20 -0800 (Thu, 19 Nov 2009) | 1 line
    
    Matrix build wasn't showing their full name in the executor list on the left.
  ........
................
  r23871 | mindless | 2009-11-19 14:42:44 -0800 (Thu, 19 Nov 2009) | 2 lines
  
  fix a couple typos in comments
................
  r23874 | mindless | 2009-11-19 15:02:11 -0800 (Thu, 19 Nov 2009) | 4 lines
  
  Allow zero for inDemandDelay in RetentionStrategy.Demand.
  Don't write "launching" in log if launch is not supported.
  Don't need to call check() every minute for NOOP strategy.
................
  r23875 | mindless | 2009-11-19 15:37:45 -0800 (Thu, 19 Nov 2009) | 9 lines
  
  [FIXED HUDSON-3890] Fix in-demand RetentionStrategy and more offline-slave fixes.
  - Use isConnecting() instead of lastConnectActivity!=null in checking forceReconnect
    param.. var never resets to null, so this prevented forceReconnect==false from ever
    reconnecting (which broken in-demand strategy since 1.302 when it started using false)
  - Only set ChannelTermination offline cause when the exception param is non-null.
    On orderly shutdown this was replacing the real cause of going offline.
  - In setNode try to delegate to RetentionStrategy rather than calling connect directly.
    Reconfiguring a node was launching slave even if it wasn't needed per its strategy.
................